CREATE DATABASE [Calculator]
GO
ALTER DATABASE [Calculator] SET COMPATIBILITY_LEVEL = 120
GO
USE [Calculator]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Historic](
	[historicId] [int] IDENTITY(1,1) NOT NULL,
	[value1] [int] NOT NULL,
	[value2] [int] NOT NULL,
	[operation] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[historicId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


